# Site settings
title: Gaming Theorist
email: JasYoung314@gmail.com
description: > # this means to ignore newlines until "baseurl:
    My blog, where I talk about math, PhD life and anything that interests me at a given moment
baseurl: "/gamingtheorist" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JasYoung314
github_username:  JasYoung314

# Build settings
markdown: kramdown


defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
        values:
            layout: "default"

